### PR TITLE
Allow configuring of debug mode

### PR DESCRIPTION
**Pull request by apurvis**
Our leanplum resurrection events seem to be getting lost; I want to be able to just turn on full logging without adding ENV variables to the `dw_runner` calls because `dw_runner` makes that really annoying.

### CODE REVIEW

**Comment by apurvis** [comment]
yeah this change gives you the option of configuring it OR using the ENV.  turned out to be sort of unnecessary given what the error turned out to be but i still think it's a worthwhile change.

**Comment by rfroetscher** [comment]
this is actually breaks backward compatability. think we should bump to 3.0

**Comment by rfroetscher** [comment]
also a CHANGELOG.md or UPGRADING.md would be good

**Comment by apurvis** [comment]
> this actually breaks backward compatibility. think we should bump to 3.0

which part?  the `True/False` stuff?  because nothing else breaks any compatibility.

**Comment by apurvis** [comment]
(and that doesn't actually break anything, though it does change behavior).  i did opt for a minor version bump over just a bugfix.

**Comment by rfroetscher** [comment]
how does that not break backwards compatibility? it used to be a string and now it is a bool. this version is not compatible with the last.

**Comment by apurvis** [comment]
well, it is ruby which kind of doesn't give a shit about types, but i see your point (esp. because other people are using and occasionally contributing to this gem).  i'll yank the 2.1.0 and replace with 3.0.0

**Comment by apurvis** [comment]
i was thinking more in terms of "almost definitely going to break old code" instead of "might, in a small % of use cases, break code" but i think everyone including me should be more liberal with major version bumps, so https://github.com/lumoslabs/leanplum_api/commit/cf1845792b6aad82ac757d7fa42ec11162506fc0

**Comment by rfroetscher** [comment]
thanks, appreciate it

**Pull request merged**
